// Inserire qui il link pubblico del Google Form quando disponibile.
const GOOGLE_FORM_URL='';
const routes=[['home','Home'],['corsi','Corsi'],['insegnanti','Insegnanti'],['news','News'],['storia','La nostra storia'],['partnership','Partnership'],['gallery','Gallery'],['contatti','Contatti'],['portale','Accesso portale']];
const courses=[
['Canto Base','Dai 6 anni · Individuale · 1 ora a settimana','Il primo passo per conoscere la propria voce. Si parte dalle basi: respirazione, intonazione, emissione vocale, articolazione e controllo della voce. Esercizi e brani adeguati all’età introducono anche l’uso del microfono e le prime esperienze di interpretazione.'],
['Canto Pro','Percorso avanzato · Individuale · 1 ora a settimana','Un percorso per approfondire la tecnica vocale e sviluppare la propria personalità artistica. Controllo delle dinamiche, estensione e fraseggio si affiancano a interpretazione, presenza scenica e scelta del repertorio, per costruire identità musicale e stile.'],
['Canto⁺','Individuale · 1 ora a settimana + teoria di gruppo','Al lavoro sulla tecnica vocale, sull’interpretazione e sulla presenza scenica si aggiungono due incontri mensili di teoria musicale di gruppo. Ritmo, lettura e fondamenti dell’armonia aiutano a comprendere i brani e a comunicare con altri musicisti.'],
['Batteria','Dai 5 anni · Individuale · 1 ora a settimana','Senso del ritmo, coordinazione e musicalità attraverso lo studio di postura, impugnatura, rudimenti, lettura ritmica e indipendenza degli arti. Le competenze vengono applicate a groove, accompagnamenti e brani di diversi generi, con un programma adattato all’allievo.'],
['Chitarra','Dai 5 anni · Individuale · 1 ora a settimana','Chitarra acustica ed elettrica: tecnica, accordi, ritmica, arpeggi, scale e repertorio. Il programma approfondisce accompagnamento, improvvisazione e uso espressivo dello strumento. Preparazione alle prove di ammissione in conservatorio in base ai requisiti dell’istituto scelto.'],
['Basso','Dai 5 anni · Individuale · 1 ora a settimana','Tecnica, precisione ritmica e capacità di accompagnamento. Si studiano impostazione delle mani, scale, arpeggi e costruzione delle linee di basso, con attenzione al groove e all’interazione con la batteria e gli altri strumenti.'],
['Pianoforte','Dai 5 anni · Individuale · 1 ora a settimana','Postura, coordinazione delle mani, lettura dello spartito, tecnica ed espressione attraverso esercizi e brani graduati. Il percorso sviluppa sensibilità musicale e autonomia, approfondendo repertorio pianistico e accompagnamento.'],
['Little Voice','Dai 3 ai 6 anni · Gruppo · 1 ora a settimana','Un primo incontro con la musica attraverso il gioco. Canzoni, movimento, attività ritmiche ed esercizi di ascolto aiutano i bambini a esplorare la voce e acquisire sicurezza nel gruppo, preparando gradualmente a un eventuale percorso individuale.'],
['Vocal Group','Diverse fasce d’età · Gruppo · 1 ora a settimana','Tecnica vocale di base, intonazione e ascolto reciproco. Attraverso brani a più voci si affrontano armonizzazioni, polifonia, equilibrio sonoro e interpretazione collettiva. Repertorio e gruppi sono adattati all’età e all’esperienza dei partecipanti.'],
['Chorus','Minimo 10 partecipanti · Gruppo · 1 ora a settimana','Un percorso corale per costruire un suono condiviso. Tecnica vocale, respirazione, intonazione e polifonia si uniscono allo studio del repertorio. Si impara ad ascoltare le altre sezioni, seguire la direzione e contribuire al risultato dell’ensemble.'],
['Musica d’insieme','Voci e strumenti · Gruppo · 1 ora a settimana','Un laboratorio per formare e far crescere una band. Cantanti e strumentisti lavorano su repertorio, arrangiamenti, precisione ritmica e interazione, sviluppando ascolto, gestione delle prove e preparazione alla performance dal vivo.'],
['Home Recording','Gruppo · 1 ora a settimana','Un’introduzione pratica alla produzione musicale: software di registrazione, schede audio, microfoni e sistemi di ascolto. Si affrontano scelta e posizionamento dei microfoni, livelli, organizzazione delle sessioni, editing e fondamenti di mix e mastering, con esercitazioni per realizzare le prime produzioni.']];
const teachers=[['Martina Giordano','Canto individuale e di gruppo'],['Rino Giglio','Batteria'],['Marcello Lachina','Chitarra · Home Recording'],['Valerio Ruvolo','Basso · Teoria musicale'],['Marcello Giordano','Pianoforte'],['Docente interno','Musica d’insieme']];
const photos=['foto 1.jpeg','goto 2.jpeg',...Array.from({length:13},(_,i)=>`foto ${i+3}.jpeg`),'innaugurazione foto.jpeg'];
const story='L’Accademia Amici del Canto nasce a Caltanissetta nel 2010 per accompagnare bambini, ragazzi e adulti nella scoperta e nello sviluppo del proprio talento musicale.';
const storyMore='Da sedici anni uniamo formazione, pratica e occasioni di confronto. Ai corsi individuali di canto e strumento affianchiamo laboratori e attività di gruppo, perché la musica sia anche un’esperienza di collaborazione e condivisione.';
const storyLast='La nostra offerta comprende percorsi con docenti qualificati, preparazione alle prove di ammissione nei conservatori italiani e opportunità di approfondimento attraverso casting, masterclass e incontri con professionisti del panorama musicale nazionale. Le occasioni di esibizione e gli spettacoli accompagnano gli allievi nella costruzione di competenze, sicurezza e identità artistica.';
const intro=(k,title,text='')=>`<div class="intro"><span class="eyebrow">Accademia Amici del Canto / ${k}</span><h1>${title}</h1>${text?`<p>${text}</p>`:''}</div>`;
const cta=()=>`<a class="button" href="${GOOGLE_FORM_URL||'#contatti'}" ${GOOGLE_FORM_URL?'target="_blank" rel="noopener"':''}>Richiedi informazioni</a>`;
function cards(list,start=0){return `<div class="grid">${list.map((c,i)=>`<article class="card"><span class="number">${String(i+1+start).padStart(2,'0')}</span><h3>${c[0]}</h3><p class="meta">${c[1]}</p><p>${c[2]}</p>${cta()}</article>`).join('')}</div>`;}
function render(){let route=location.hash.slice(1)||'home';if(!routes.some(r=>r[0]===route))route='home';document.getElementById('navigation').innerHTML=routes.map(([id,label])=>`<a href="#${id}" ${id===route?'class="active" aria-current="page"':''}>${label}</a>`).join('');let html='';
if(route==='home')html=`<section class="hero"><img data-image="foto 14.jpeg" alt="Allievi dell’accademia sul palco"><div class="hero-copy"><span class="eyebrow">Caltanissetta · Dal 2010</span><h1>Dai voce<br>alla tua musica.</h1><p>Canto, strumenti e musica d’insieme.<br>Un percorso per crescere, esprimerti e salire sul palco.</p><a class="button" href="#corsi">Scopri i corsi</a> <a class="button secondary" href="#contatti">Richiedi una prova gratuita</a></div></section><section class="section"><span class="eyebrow">Il tuo percorso</span><h2>Una passione.<br>Tante possibilità.</h2><div class="grid">${[['Canto','Tre livelli individuali e percorsi vocali di gruppo.'],['Strumenti','Chitarra, basso, batteria e pianoforte.'],['Laboratori','Musica d’insieme e Home Recording.']].map(([t,p])=>`<a class="course-summary" href="#corsi"><h3>${t}</h3><p>${p}</p><strong>Esplora i corsi</strong></a>`).join('')}</div></section><section class="dark"><div class="section split"><div><span class="eyebrow">La nostra storia</span><h2>La musica cresce<br>quando si condivide.</h2><p>${story}</p><div class="stats"><div><strong>2010</strong>Anno di fondazione</div><div><strong>16</strong>Anni di formazione</div></div><a class="button" href="#storia">Conosci l’accademia</a></div><img data-image="foto 7.jpeg" alt="Allievi e docenti dopo uno spettacolo" loading="lazy"></div></section><section class="section"><span class="eyebrow">Inizia da qui</span><h2>Conosciamoci con<br>una prova gratuita.</h2><p>Contattaci per individuare il percorso adatto a te e concordare la tua prima esperienza in accademia.</p>${cta()}</section>`;
if(route==='corsi')html=intro('Corsi','Trova il tuo percorso.','Dalle prime note alla performance: programmi adattati all’età, all’esperienza e agli obiettivi di ogni allievo.')+`<section class="section"><span class="eyebrow">Canto e strumenti</span><h2>Corsi individuali</h2>${cards(courses.slice(0,7))}</section><section class="section"><span class="eyebrow">Imparare insieme</span><h2>Corsi di gruppo</h2>${cards(courses.slice(7),7)}</section>`;
if(route==='insegnanti')html=intro('Insegnanti','Le persone dietro la musica.')+`<section class="section"><div class="grid">${teachers.map(([n,s])=>`<article class="card"><h3>${n}</h3><p class="meta">${s}</p></article>`).join('')}</div></section>`;
if(route==='news')html=intro('News','News & eventi.')+`<section class="section" aria-label="Notizie"></section>`;
if(route==='storia')html=intro('La nostra storia','Dal 2010, insieme alla musica.')+`<section class="section split"><div><p>${story}</p><p>${storyMore}</p><p>${storyLast}</p></div><img data-image="innaugurazione foto.jpeg" alt="Un momento dell’inaugurazione dell’accademia"></section>`;
if(route==='partnership')html=intro('Partnership','Connessioni che fanno crescere.')+`<section class="section"><div class="grid">${[['EMME STUDIO','LOGO 1.png','Produzione musicale e studio di registrazione.'],['SPAZIO VUOTO','LOGO 2.jpeg','Scuola di recitazione.'],['GROOVE IN ART','LOGO 3.jpeg','Strumenti musicali.']].map(([n,img,p])=>`<article class="card partner"><img data-image="${img}" alt="Logo ${n}"><h3>${n}</h3><p>${p}</p></article>`).join('')}</div></section>`;
if(route==='gallery')html=intro('Gallery','La nostra musica, in immagini.','Spettacoli, incontri e momenti condivisi.')+`<section class="section"><div class="gallery">${photos.map((p,i)=>`<button data-photo="${i}" aria-label="Apri fotografia ${i+1}"><img data-image="${p}" alt="${p.includes('innaugurazione')?'Inaugurazione dell’accademia':'Un momento degli spettacoli dell’accademia'}" loading="lazy"></button>`).join('')}</div></section>`;
if(route==='contatti')html=intro('Contatti','Parliamo della tua musica.','Richiedi informazioni sui corsi o concorda una prova gratuita.')+`<section class="section contact-grid"><div><h2>Vieni a conoscerci.</h2><p>Via Ruggero Settimo SNC<br>Caltanissetta, CL 93100</p><a class="button secondary" href="https://maps.app.goo.gl/jJHT9J7eJ5V5qmfk8" target="_blank" rel="noopener">Indicazioni su Google Maps</a><h3>Orari di apertura</h3><p>Lunedì – venerdì<br>9:00–13:00 · 15:00–20:00</p></div><div class="card"><h3>Informazioni e prova gratuita</h3>${GOOGLE_FORM_URL?cta():''}<p><a href="tel:+393898227001">+39 389 822 7001</a><br><a href="tel:+393881988602">+39 388 198 8602</a></p><a href="mailto:accademiaamicidelcanto@gmail.com">accademiaamicidelcanto@gmail.com</a><p><a href="https://wa.me/393898227001" target="_blank" rel="noopener">Scrivici su WhatsApp</a></p><hr><p><a href="https://www.instagram.com/accademia_amicidelcanto/" target="_blank" rel="noopener">Instagram</a> · <a href="https://www.facebook.com/share/1DyVE8s6Sw/" target="_blank" rel="noopener">Facebook</a></p></div></section>`;
if(route==='portale')html=intro('Accesso portale','Il tuo spazio, prossimamente.')+`<section class="section"><div class="notice"><h2>Portale in arrivo</h2><p>L’accesso al portale dell’accademia sarà disponibile prossimamente.</p><a class="button" href="#contatti">Contatta l’accademia</a></div></section>`;
document.getElementById('content').innerHTML=html;document.querySelectorAll('[data-image]').forEach(el=>el.src=ASSETS[el.dataset.image]);document.querySelectorAll('[data-photo]').forEach(b=>b.addEventListener('click',()=>openPhoto(Number(b.dataset.photo))));document.title=routes.find(r=>r[0]===route)[1]+' | Accademia Amici del Canto';document.getElementById('navigation').classList.remove('open');document.getElementById('menu').setAttribute('aria-expanded','false');window.scrollTo(0,0);}
let currentPhoto=0;const dialog=document.getElementById('lightbox');function openPhoto(i){currentPhoto=(i+photos.length)%photos.length;dialog.querySelector('img').src=ASSETS[photos[currentPhoto]];dialog.querySelector('img').alt=`Fotografia ${currentPhoto+1} dell’accademia`;if(!dialog.open)dialog.showModal();}document.getElementById('close').onclick=()=>dialog.close();document.getElementById('previous').onclick=()=>openPhoto(currentPhoto-1);document.getElementById('next').onclick=()=>openPhoto(currentPhoto+1);dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});dialog.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')openPhoto(currentPhoto-1);if(e.key==='ArrowRight')openPhoto(currentPhoto+1)});document.getElementById('menu').onclick=()=>{const open=document.getElementById('navigation').classList.toggle('open');document.getElementById('menu').setAttribute('aria-expanded',String(open))};document.getElementById('year').textContent=new Date().getFullYear();window.addEventListener('hashchange',render);render();
